######################################################################
# Automatically generated by qmake (2.01a) ? 11 26 16:40:22 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += thread.h thread_form.h
SOURCES += main.cpp thread.cpp thread_form.cpp
DESTDIR=../../bin
